FROM mcr.microsoft.com/vscode/devcontainers/universal:2-linux
RUN sudo apt-get -y update 
#RUN sudo apt-get -y install gnuplot
#RUN sudo wget http://github.com/JSBSim-Team/jsbsim/releases/download/v1.1.13/JSBSim-devel_1.1.13-986.focal.amd64.deb
#RUN apt install JSBSim-devel_1.1.13-986.focal.amd64.deb
#RUN sudo apt-get install libboost-all-dev
#RUN sudo apt-get install libgl1-mesa-dev
#RUN sudo apt-get install libopenal-dev
